#!/bin/bash
IP=10.2.255.254
COUNT=30
for myHost in $IP
do
  msg=$(ping -q -n -c $COUNT $myHost | grep "packet loss" | cut -d " " -f 6 | cut -d "%" -f1)
  ssg=$(ping -q -n -c 5 10.2.10.14 | grep "time" | cut -d " " -f 10 | cut -d "%" -f1)
echo "$msg $ssg"
done
