#!/bin/bash
#IP=www.google.co.in
IP=10.2.255.254
COUNT=30
cd $(dirname "$0")
SCRIPTNAME=$(basename "$0")
for myHost in $IP
do
  msg=$(ping -c $COUNT $myHost| grep 'loss' | awk -F',' '{ print $3}')
  ssg=$(ping -c $COUNT $myHost  | grep 'received' | awk -F',' '{ print $4}')
 #echo "($myHost $COUNT) $msg"  
  if [ $msg = 0% ]; then
    echo "node $IP is up" 
    else
    echo "node $IP is down"
    fi
  if [ $ssg => 9000 ]; then
    echo "node $IP is on" 
    else
    echo "node $IP is off"
    fi
  #count=$(ping -c $COUNT $myHost | grep 'received' | awk -F',' '{ print $2 }' | awk '{ print $1 }')
  #if [ $count -eq 0 ]; then
    #100% failed
    #echo "Host : $myHost is down (ping failed) at $(date)" | mail -s "$SUBJECT" $EMAILID
  #fi
done
